INSERT INTO "categoria" VALUES(1,'Celulares e Tablets',NULL);
INSERT INTO "categoria" VALUES(2,'Automóveis',NULL);
INSERT INTO "categoria" VALUES(4,'Música',NULL);
INSERT INTO "categoria" VALUES(5,'Computadores',NULL);
INSERT INTO "categoria" VALUES(7,'Eletrônicos',NULL);
INSERT INTO "categoria" VALUES(8,'Eletrodomésticos',NULL);
INSERT INTO "categoria" VALUES(9,'Esportes',NULL);
INSERT INTO "categoria" VALUES(10,'Para Casa',NULL);
INSERT INTO "categoria" VALUES(11,'Moda e Beleza',NULL);
INSERT INTO "categoria" VALUES(12,'Infantil',NULL);
INSERT INTO "categoria" VALUES(13,'Pet',NULL);
INSERT INTO "categoria" VALUES(14,'Serviços',NULL);
