INSERT INTO "categoria" VALUES('1','Informática e Tecnologia',NULL);
INSERT INTO "categoria" VALUES('2','Casa e Escritório',NULL);
INSERT INTO "categoria" VALUES('3','Cultura e Diversão',NULL);
INSERT INTO "categoria" VALUES('4','Ferramentas',NULL);
INSERT INTO "categoria" VALUES('5','Automotivo',NULL);
INSERT INTO "categoria" VALUES('6','Esportes',NULL);
INSERT INTO "categoria" VALUES('7','Saúde',NULL);
INSERT INTO "categoria" VALUES('8','Infantil',NULL);
INSERT INTO "categoria" VALUES('1.1','Computadores','1');
INSERT INTO "categoria" VALUES('1.2','Tablets','1');
INSERT INTO "categoria" VALUES('1.3','Telefones e Celulares','1');
INSERT INTO "categoria" VALUES('1.4','Cine & Foto','1');
INSERT INTO "categoria" VALUES('1.5','Áudio','1');
INSERT INTO "categoria" VALUES('1.6','TV e Vídeo','1');
INSERT INTO "categoria" VALUES('2.1','Eletrodomésticos','2');
INSERT INTO "categoria" VALUES('2.2','Móveis','2');
INSERT INTO "categoria" VALUES('2.3','Eletroportáteis','2');
INSERT INTO "categoria" VALUES('2.4','Utilidades Domésticas','2');
INSERT INTO "categoria" VALUES('2.5','Cama, mesa e banho','2');
INSERT INTO "categoria" VALUES('2.6','Ar e ventilação','2');
INSERT INTO "categoria" VALUES('3.1','Games','3');
INSERT INTO "categoria" VALUES('3.2','Filmes e Música','3');
INSERT INTO "categoria" VALUES('3.3','Livros','3');
INSERT INTO "categoria" VALUES('3.4','Papelaria','3');
INSERT INTO "categoria" VALUES('4.1','Elétricas','4');
INSERT INTO "categoria" VALUES('4.2','Manuais','4');
INSERT INTO "categoria" VALUES('4.3','Pneumáticas','4');
INSERT INTO "categoria" VALUES('4.4','Lavadoras de Pressão','4');
INSERT INTO "categoria" VALUES('4.5','Jardinagem','4');
INSERT INTO "categoria" VALUES('4.6','Consumíveis','4');
INSERT INTO "categoria" VALUES('4.7','Ferramentas de Medição','4');
INSERT INTO "categoria" VALUES('4.8','Compressores de Ar e Acessórios','4');
INSERT INTO "categoria" VALUES('4.9','Acessórios','4');
INSERT INTO "categoria" VALUES('5.01','Veículos','5');
INSERT INTO "categoria" VALUES('5.2','Pneus, rodas e calotas','5');
INSERT INTO "categoria" VALUES('5.3','GPS','5');
INSERT INTO "categoria" VALUES('5.4','Óleos e Fluídos','5');
INSERT INTO "categoria" VALUES('5.5','Limpeza de Automóveis','5');
INSERT INTO "categoria" VALUES('5.6','Serviços','5');
INSERT INTO "categoria" VALUES('5.7','Som automotivo','5');
INSERT INTO "categoria" VALUES('5.8','Acessórios para moto','5');
INSERT INTO "categoria" VALUES('5.9','Acessórios em geral','5');
INSERT INTO "categoria" VALUES('9','Serviços',NULL);
INSERT INTO "categoria" VALUES('10','Lazer',NULL);
INSERT INTO "categoria" VALUES('6.1','Bicicletas','6');
INSERT INTO "categoria" VALUES('6.2','Fitness','6');
INSERT INTO "categoria" VALUES('6.3','Futebol','6');
INSERT INTO "categoria" VALUES('6.4','Camping','6');
INSERT INTO "categoria" VALUES('6.5','Praia e Piscina','6');
INSERT INTO "categoria" VALUES('6.6','Calçados','6');
INSERT INTO "categoria" VALUES('6.7','Mochilas','6');
INSERT INTO "categoria" VALUES('6.8','Artes Marciais','6');
INSERT INTO "categoria" VALUES('6.9','Monitores Cardíacos','6');
INSERT INTO "categoria" VALUES('7.1','Balanças','7');
INSERT INTO "categoria" VALUES('7.2','Higiene','7');
INSERT INTO "categoria" VALUES('7.3','Massageadores','7');
INSERT INTO "categoria" VALUES('7.4','Medidores de Pressão','7');
INSERT INTO "categoria" VALUES('7.5','Medidor de Glicose','7');
INSERT INTO "categoria" VALUES('8.1','Bebês','8');
INSERT INTO "categoria" VALUES('8.2','Brinquedos','8');
INSERT INTO "categoria" VALUES('5.100.','teste 5.10','5');
